feature/add course-icon resolve #10
EduardDE7/nova-team-crm-client pull request #16
Opened 2024-02-16 10:46 UTC by andreyfeel83

![image](https://github.com/EduardDE7/nova-team-crm-client/assets/120964953/4da15652-cb1c-4673-b037-da3f823c8575)

create reusable course-icon component 
change color by props

2024-02-17 03:17 UTC, EduardDE7 requested changes

2024-02-17 03:17 UTC, EduardDE7 commented on .vscode/extensions.json
remove extensions.json from commit

2024-02-17 09:38 UTC, coldnanee approved these changes

2024-02-17 09:38 UTC, coldnanee approved these changes

2024-02-17 11:55 UTC, EduardDE7 approved these changes

2024-02-18 19:15 UTC, coldnanee requested changes
remove course-icon from shared
you need to past it into:

entities/course/ui/course-icon

2024-02-18 19:16 UTC, coldnanee requested changes
add storybook's stories

2024-02-19 17:50 UTC, closed without merging